version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - "127.0.0.1:5601:5601"
  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    volumes:
      - minio-data:/data
    ports:
      - "127.0.0.1:9000:9000"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sample-root-password
      MYSQL_DATABASE: sample-database
      MYSQL_USER: sample-user
      MYSQL_PASSWORD: sample-password
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "127.0.0.1:3306:3306"
  adminer:
    image: adminer
    ports:
      - "8888:8080"
  app:
    build: ./docker/app/
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - .:/workspace:cached
    ports:
      - "8080:8080"
      - "3000:3000"

volumes:
  es-data:
    driver: local
  minio-data:
    driver: local
  mysql-data:
    driver: local
